spring.application.name=kafka-order-processing-demo
spring.kafka.bootstrap-servers=${KAFKA_HOST:backend-kafka}:${KAFKA_PORT:9092}
spring.kafka.consumer.auto-offset-reset=earliest
logging:
  level:
    org.apache.kafka: WARN
    org.springframework.kafka: WARN