spring.application.name=learning-kafka
spring.kafka.bootstrap-servers=host.docker.internal:9092
spring.kafka.consumer.auto-offset-reset=earliest
logging:
  level:
    org.apache.kafka: WARN
    org.springframework.kafka: WARN